### PR TITLE
make sure HOME is set when using pip

### PR DESCRIPTION
**Pull request by kisoku**

### CODE REVIEW

**Comment by boxidau** [comment]
:+1: I'm running into this issue too

**Comment by coderanger** [comment]
@boxidau Can you pastebin the error you are getting? I've got a deep fix in the works but I can't get a repro that actually fails (not just pip printing warnings)/

**Comment by boxidau** [comment]
Unfortunately it's just gone off the top of my terminal buffer :/ and I'm trying to implement a fix for a customer and am working around for now. If i run into it again I'll be sure to send it your way.

To recreate: I have a cookbook calling supervisor::default (which uses the old python cookbook) then another calling poise-python::default and later doing a pip_package with user and group. So a bit messy with the old and new cookbooks.

**Comment by coderanger** [comment]
A deeper fix is now in poise and poise-languages. Will be rolled out to all of the language command shell_out wrappers together.

**Pull request closed without merging**
