### PR TITLE
fix version comparison

### PR DESCRIPTION
**Pull request by bvold**

### CODE REVIEW

**Comment by coderanger** [comment]
I'm going to suggest that `Gem::Version.new` doesn't work in Python code :)

**Comment by coderanger** [comment]
The code you edited it a large heredoc containing Python code used to simulate a dry-run mode of Pip for version checks. The tests passed because, for security reasons, I can't run my integration test suite on PRs.

**Comment by bvold** [comment]
Now I feel dumb. lol

**Comment by coderanger** [comment]
No worries, that bit of code is one of the more intricate and magical things in poise-python, much of what it does seems awkward but has Weird Reasons™.

**Pull request closed without merging**
